function name() {
    alert("hello world");
    // 当一个变量没有声明，没有赋值。输出的结果就是 undefined 
}
// var num=10;
// var isture=false;
// var nulls=null;
// var undefineds=undefined;
// var name="your name";
// var obj=new Object(); 
// console.log(typeof num);
// console.log(typeof isture);
// console.log(typeof nulls);
// console.log(typeof undefineds);
// console.log(typeof name);
// console.log(typeof obj);

// console.log(isNaN(NaN));
// console.log(isNaN(10));
// console.log(isNaN("10"));
// console.log(isNaN("blue"));
// console.log(isNaN(true));
// var result = Number.MAX_VALUE + Number.MAX_VALUE;
// alert(isFinite(result));


// AO{

// }


