// var num=10;
// var num2=20;
// num++;
// var num3=num+num2;
// console.log(num3);
// console.log(num);

// var num = 10;
// console.log(num.toString(2));
// console.log(num.toString(8));
// console.log(num.toString(10));
// console.log(num.toString(16));

// var oldValue = -64;
// var newValue = oldValue >>> 5;
// console.log(newValue);

// var num=10;
// var num2="10";
// if(num===num2){
//     console.log("this is yes");
// }
// else{
//     console.log("this is No");
// }

// var found=true;
// var result=(found && someUndefinedVariable);
// alert(result);

// var num=12;
// var num2=10;
// var message="the sum of 5 and 10 is"+(num+num2);
// console.log(message);

// var result="Brick".toLowerCase()<"alphabet".toLowerCase();
// alert(result);
// for (var index = 0; index <= 100; index++) {
//     if(index>100)
//     {
//         console.log(index);    
//     }
//     else{
//         console.log("only hava hundred");
//     }
// }

// var score=new Array(30,20,30,60,70);
// // 数组下标的是从0开始的 ;
// var max =0;
// for (var index = 0; index <= 100; index++) {
//    if(score[index]>max)
//    {
//        max=score[index];
//    }
// }
// console.log(max);

// var score=new Array20[10];

// var number = prompt("请输入你的年龄");        // input keyword is prompt. but output format is typeofstring
// var number3=parseInt(prompt("请输入你的年龄"));
// var number2 = 30 - number;
// alert("你的年龄是" + number2 + "岁");

// var num = parseInt(prompt("please enter first number"));
// var num2 = parseInt(prompt("please enter second number"));

// if (num > num2) {
//     if (num % 2 === 0) {
//         alert(num + " is max evenValue")
//     }
//     else{
//         alert(num + " is max oddValue")
//     }
// }
// else {
//     if (num2 % 2 === 0) {
//         alert(num2 + " is max evenValue")
//     }
//     else{
//         alert(num2 + " is max oddValue")
//     }
// }

// alert("max value is "+max);

//  求润年
// var year=parseInt(prompt("please enter an year"));

// if (year%4===0&&year%100!==0||year%400===0){
//     alert(year+"is LeapYear");
// }
// else{
//     alert(year+"is CommonYear");
// }

// var score=parseInt(prompt("please enter an score"));
// switch(true){
//     case score>90:      // case connot do judge;
//     alert("A");
//     break;

//     case score>80:
//     alert("B");
//     break;

//     case score>70:
//     alert("C");
//     break;

//     case score>60:    
//     alert("D");    
//     break;

//     case score<60:    
//     alert("不及格，回去补考");    
//     break;
// }

// var count=1;
// while(count<=100){
//     console.log("第"+(count+1)+"次计数");
//     count++;
// }

// 求6的阶乘

// var num = 1;
// var product = 1;
// while (num < 7) {
//     product *= num;
//     console.log(product);
//     num++;
// }

// 求1-100的偶数和
// var num=0;
// var sum=0;
// while(num<101){
//     sum+=num;
//     num+=2;
//     console.log(sum);
// }

// var account=prompt("please enter your account");
// var password=parseInt(prompt("please enter your password"));

// while(account!=="admin"||password!=456){
//     alert("输入不正确");  
//     account=prompt("please enter your account");
//     password=parseInt(prompt("please enter your password"));     
// }
// console.log("登入成功");

// document.write("<a href='https://www.baidu.com'>百度</a>");
//  for(var i=1;i<10;i++){

//     for(var j=1;j<=i;j++)
//     {
//         document.write(i+"*"+j+"="+(i*j));
//         document.write("&nbsp &nbsp &nbsp");
//     }
//     document.write('<br/>');
//  }


// var i=1;
// var j=0;
// for(i=0;i<101;i++){
//     j+=i;   
//     if(j%10==3){
//         console.log(j);
//         break;
//     }
// }


// var array=[15,45,66,89];














